### ISSUE TITLE
aflat ignores exclhi and excllo

### ISSUE THREAD

**Issue by nbingham1** [asyncvlsi/act#10]
```
defproc test(bool a, b)
{
	spec {
		exclhi(a, b)
	}
	prs
	{
		a => b-
	}
}

test t;
```

```
$ aflat tmp.act 
"t.a"->"t.b"-
~("t.a")->"t.b"+
```

**Comment by rmanohar** [comment]
That's correct behavior. You're supposed to say  mk_exclhi(a,b). The "exclhi(a,b)" is viewed as something that the circuit has to guarantee on its own (e.g. for a dualrail code).

**Comment by nbingham1** [comment]
Isn't prsim supposed to issue a warning if the "exclhi" spec is violated?

**Comment by rmanohar** [comment]
No, they are simply stripped out for prsim, as it doesn't have any support for invariant assertions.

**Comment by nbingham1** [comment]
So what are exclhi and excllo connected to then? Is it just a TODO at the moment?

**Comment by rmanohar** [comment]
They are used by lvp. More generally, the entire spec section will be re-done in the next year.
