### ISSUE TITLE
prsim: promt does not appear

### ISSUE THREAD

**Issue by olerichter** [asyncvlsi/act#21]
**Describe the bug**
when starting prsim without anything the promt does not appear

**To Reproduce**
compile fresh of the git both mac or centos
run prsim
get an unresponsive terminal

**Expected behavior**
EDIT: should it display usage, or should there be a promt, i am a bit confused at the moment

**Screenshots**

**Computer setup (please complete the following information):**
 - centos7 with gcc7.3
 - macos 10.15 with clang 12.0.0
 - grace

**Comment by rmanohar** [comment]
Strange. Can you try it with a .prs file? I seem to get a prompt... I used a simple file
```
a -> b-
```
and I see the same expected behavior.

**Comment by olerichter** [comment]
sorry may brain short circuited a bit, i was trying to simplify+reproduce a different issue, and did not realise that it obviously does not make sense to run prsim with act files..., somewhere on my reproduction tries i must have switched.

but yes prsim -r test.prs (so not act content) works fine

**Comment by olerichter** [comment]
I know now what trew me of,
if you ctrl-C on prsim, the terminal becomes unresponsive but does not terminate,
i will close this issue
