### ISSUE TITLE
aflat doesn't generate rules for pass transistors

### ISSUE THREAD

**Issue by nbingham1** [asyncvlsi/act#7]
```
defproc test(bool a, b, c, x, y)
{
  prs {
    passn(a, b, c)
    x -> y-
  }
}

test t;
```

```
$aflat tmp.act 
"t.x"->"t.y"-
```

**Comment by nbingham1** [comment]
Perhaps if this is intended, then issue a warning when encountering pass transistors to be expanded instead of failing silently.

**Comment by rmanohar** [comment]
This has been fixed to replicate the old ACT behavior, but the prs model isn't really right. The real fix in progress is to change the output and then fix the simulator to do the right thing... but the old behavior has been restored now.
